# Generated by Django 3.2.20 on 2025-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='lending_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='借出时间'),
        ),
    ]
